arb-dir: lib/l10n/arb
output-dir: lib/l10n/generated
template-arb-file: app_en.arb
output-localization-file: locale.dart
output-class: Loc
synthetic-package: false
nullable-getter: false
untranslated-messages-file: l10n_missing.txt